# Autogenerated by devscripts/update-version.py

__version__ = '2026.05.24.1'

RELEASE_GIT_HEAD = '18352df68283b470ab04e626c3c2b1a2ac7b35d1'

VARIANT = None

UPDATE_HINT = None

CHANNEL = 'stable'

ORIGIN = 'local'

_pkg_version = '2026.05.24.1'
